---
title: "Descriptive stats using MetaboAnalyst"
output: html_notebook
---

```{r}
# Recreate tutorial at https://www.metaboanalyst.ca with own dataset
library(MetaboAnalystR)

library(dplyr)
library(tidyr)
library(stringr)
```

```{r}
test_data_file <- "~/git_repo/data_examples/test.tsv"
figure_folder <- "~/local_files/analyst_out/basic_stats"
if(!dir.exists(figure_folder)) dir.create(figure_folder, recursive = TRUE)
```

```{r}
metab_data <- test_data_file %>%
  read.table(sep="\t", stringsAsFactors=FALSE, header=TRUE) %>%
  rename(Metabolite = X, MetaboGroup = X.1) %>%
  pivot_longer(c(-Metabolite, -MetaboGroup)) %>%
  mutate(
    Condition = str_extract(name, 'Condition(A|B)'),
    Replicate = case_when(
      grepl('\\.1', name) ~ 'Batch_2',
      grepl('\\.2', name) ~ 'Batch_3',
      TRUE ~ 'Batch_1'
    ),
    Subject = paste(Condition, Replicate, sep="_")
  ) %>%
  select(-name)

head(metab_data)
```

```{r}
analyst_compatible_data <- "~/local_files/local_data/reshaped_metabo.csv"
  
metab_data %>%
  select(-MetaboGroup, -Replicate)  %>%
  select(Subject, Condition, Metabolite, value)  %>%
  pivot_wider(names_from=Metabolite) %>%
  write.csv(analyst_compatible_data, row.names=FALSE)
```

```{r}
mSet <- NULL # Have to reset otherwise the app resurrects old instance from global when chunk is rerun
anal.type <- "msetquea"
msg.vec <- list()

mSet <- InitDataObjects("conc", "stat") %>%
  Read.TextData(analyst_compatible_data, "rowu") %>%
  SanityCheckData()
```

```{r}
# Preprocess data
mSet <- mSet %>%
  ReplaceMin() %>%
  FilterVariable("iqr", "F", 25) %>%
  PreparePrenormData() %>%
  Normalization("MedianNorm", "LogNorm", "NULL", ratio=FALSE, ratioNum=20)
```

```{r}
mSet <- PlotNormSummary(mSet, file.path(figure_folder, "normalization_summary"), "png")
```

```{r}
mSet <- PlotSampleNormSummary(mSet, file.path(figure_folder, "sample_normalization"), "png")
```

```{r}
mSet <- FC.Anal(mSet, 2.0, 0)
mSet <- PlotFC(mSet, file.path(figure_folder, "fold_changes"), "png")
```

```{r}
mSet <- Ttests.Anal(mSet, F, 0.05, FALSE, TRUE)
mSet <- PlotTT(mSet, file.path(figure_folder, "t_tests"), "png")
```

```{r}
mSet <- mSet %>%
  PCA.Anal() %>%
  PlotPCAPairSummary(file.path(figure_folder, "pca_pair"), "png", 72, width=NA, 5) %>%
  PlotPCAScree(file.path(figure_folder, "pca_scree"), "png", 72, width=NA, 5) %>%
  PlotPCA2DScore(file.path(figure_folder, "pca_score2d"), "png", 72, width=NA, 1, 2, 0.95, 1, 0) %>%
  PlotPCALoading(file.path(figure_folder, "pca_loading"), "png", 72, width=NA, 1, 2) %>%
  PlotPCABiplot(file.path(figure_folder, "pca_biplot"), "png", 72, width=NA, 1, 2) %>%
  PlotPCA3DScoreImg(file.path(figure_folder, "pca_score3d"), "png", 72, width=NA, 1,2,3, 40)
```

```{r}
mSet <- mSet %>%
  PLSR.Anal(reg=TRUE) %>%
  PlotPLSPairSummary(file.path(figure_folder"pls_pair"), "png", 72, width=NA, 5) %>%
  PlotPLS2DScore(file.path(figure_folder"pls_score2d"), "png", 72, width=NA, 1,2,0.95,1,0) %>%
  PlotPLS3DScoreImg(file.path(figure_folder"pls_score3d"), "png", 72, width=NA, 1,2,3, 40) %>%
  PlotPLSLoading(file.path(figure_folder"pls_loading"), "png", 72, width=NA, 1, 2) %>%
```