---
title: "Metabolomic analysis powered by MetaboAnalyst, made flexible"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      toc_collapsed: true
---

```{r}
# Source scripts that bundle MetaboAnalyst functions

source("../scripts/descriptive_stats.r", chdir=TRUE)
```

```{r}
# Specify output location and create if not existent

local_folder <- "/home/rstudio/local_files/test_output"
if(!dir.exists(local_folder)) dir.create(local_folder)
```

```{r}
# Parse test input

test_data_file <- "~/git_repo/data_examples/test.tsv"
metabo_data <-standardize_metabo_data(test_data_file)

head(metabo_data)
```

```{r}
# Convert input to an mSet object

mSet <- convert_cc_to_mSet(metabo_data)
```

```{r}
# Normalize input data

mSet <- normalize_mSet(mSet)
```

```{r}
# Save normalization report

mSet <- PlotSampleNormSummary(mSet, file.path(local_folder, "sampleNorm"), "pdf")
```

```{r}
# Calculate basic descriptive statistics

stat_results <- calcMetaboStat(mSet)

#head(stat_results$data)
```



```{r}
# Show a volcano plot of the results

plotMetaboVolcano(stat_results)
```